package galatasaray.stepdefinition;

import static org.testng.Assert.assertTrue;

import java.util.List;
import java.util.Locale;
import java.util.Random;

import org.apache.log4j.Logger;
import org.openqa.selenium.InvalidArgumentException;
import org.openqa.selenium.WebElement;
import org.testng.Assert;

import com.github.javafaker.Faker;

import core.AppiumInstance;
import core.BusinessFunction;
import cucumber.TestContext;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import utilities.ConfigReader;
import utilities.ReadOTPFromAndroid;

public class HomeScreenSteps {

	private static Logger log = Logger.getLogger(HomeScreenSteps.class);
	private static final int TIMEOUT = Integer.parseInt(ConfigReader.getProperty("timeout"));
	private static String appActivity = ConfigReader.getProperty("appActivity");

	private TestContext testContext;

	public HomeScreenSteps(TestContext testContext) {
		this.testContext = testContext;
	}

	@Given("I open the app")
	public void i_open_the_app() {

		testContext.getCoreFunctions().waitTillActivity(TIMEOUT, appActivity);
		
		//adding some sleep for application to open properly
		try {
			Thread.sleep(10000);
		} catch (InterruptedException ignore) {
		}
		
		log.info("application opened sucessfully");
	}

	@Then("I should see the profile picture")
	public void i_should_see_the_profile_picture() {

		boolean status = testContext.getPage().HomePage().isProfilePictureDisplayed();
		Assert.assertTrue(status);
	}

	@Then("I should see the profile name")
	public void i_should_see_the_profile_name() {

		boolean status = testContext.getPage().HomePage().isProfileNameDisplayed();
		Assert.assertTrue(status);
	}

	@When("I click on signin button")
	public void i_click_on_signin_button() {
		
		boolean status = testContext.getPage().HomePage().isLoginBtnDisplayed();
		Assert.assertTrue(status);

		testContext.getPage().HomePage().clickOnLoginBtn();
		
	}

	@Then("signin page should be displayed")
	public void signin_page_should_be_displayed() {

		boolean status = testContext.getPage().SignInPage().isPhoneNoInputDisplayed();
		Assert.assertTrue(status);
	}

	
	@When("I enter phoneno as {long}")
	public void i_enter_phoneno_as(Long phoneNo) {
		
		testContext.getPage().SignInPage().enterPhoneNo(String.valueOf(phoneNo));
	}

	@When("I enter valid phoneno")
	public void i_enter_valid_phoneno() {

		long phoneNo = new Random().nextInt(9003928) + 6190000009l;
		log.info("generating random mobile number " + phoneNo);
		testContext.getPage().SignInPage().enterPhoneNo(String.valueOf(phoneNo));
	}

	@When("I enter wrong OTP {int}")
	public void i_enter_wrong_OTP(Integer int1) {

		testContext.getPage().SignInPage().enterOTP(String.valueOf(int1));
	}

	@Then("I should get wrong code try again message")
	public void i_should_get_wrong_code_try_again_message() {

		String text = testContext.getPage().CommonPageElements().getErrorMessageText();
		Assert.assertEquals(text, "Yanlış kod. Tekrar deneyiniz.");
	}

	@When("I click on next button")
	public void i_click_on_next_button() {

		testContext.getPage().CommonPageElements().clickNextBtn();
	}

	@Then("I accept the contract")
	public void i_accept_the_contract() {

		testContext.getPage().CommonPageElements().clickOnYesBtn();

		testContext.getPage().CommonPageElements().clickOnYesBtn();
	}

	@Then("I select gender as")
	public void i_select_gender_as(io.cucumber.datatable.DataTable dataTable) {

		boolean status = testContext.getPage().HomePage().isGenderDisplayed();
		Assert.assertTrue(status);
		try {
			testContext.getPage().HomePage().selectGender(dataTable.asList().get(0));
		} catch (InvalidArgumentException e) {
	
		}
	}

	@Then("I select my birthdate as")
	public void i_select_my_birthdate_as(io.cucumber.datatable.DataTable dataTable) {

		// TODO
		testContext.getPage().DatePicker().selectDOB(dataTable.asList().get(0));
	}

	@Then("I should see incorrect format popup")
	public void i_should_see_incorrect_format_popup() {

		boolean status = testContext.getPage().CommonPageElements().isAlertDisplayed();
		Assert.assertTrue(status);
		String popupText = testContext.getPage().CommonPageElements().getAlertText();
		Assert.assertEquals(popupText, "Lütfen cep telefonu numaranızı başında 0 olmadan girin.");
	}

	@When("I should see the autogenerated message")
	public void i_should_see_the_autogenerated_message() {

		boolean status = testContext.getPage().HomePage().isAutoMessageCardDisplayed();
		Assert.assertTrue(status);

	}

	@When("I click on the {string} message card")
	public void i_click_on_the_message_card(String string) {

		testContext.getPage().HomePage().clickOnMessageCard(string);
	}

	@Then("message {string} should be sent")
	public void message_should_be_sent(String string) {

		boolean status = testContext.getPage().HomePage().isTextDisplayedAsCardMessage(string);
		Assert.assertTrue(status);
	}

	@Then("I choose my favourite footballer")
	public void i_choose_my_favourite_footballer() {

		testContext.getPage().HomePage().selectPlayer("Emre Akbaba");
	}

	@Then("I should receive a reply message")
	public void i_should_receive_a_reply_message() {
		// TODO
	}

	@Then("I enter firstName and lastName")
	public void i_enter_firstName_and_lastName(io.cucumber.datatable.DataTable dataTable) {

		List<List<String>> data = dataTable.asLists();

		for (List<String> temp : data) {
			testContext.getPage().HomePage().enterFirstAndLastName(temp.get(0), temp.get(1));
		}

		i_click_on_next_button();

	}
	
	@When("select country as {string} with country code as {string}")
	public void select_country_as(String country,String countryCode) {
	   
		testContext.getPage().SignInPage().clickOnCountryCode();
		testContext.getPage().CountryCodeSearchPage().enterSearchKeyword(country);
		testContext.getPage().CountryCodeSearchPage().clickOnSearchResults(country);
		
		String countryCodeSelected = testContext.getPage().SignInPage().getSelectedCountryCode();
		assertTrue(countryCodeSelected.contains(countryCode));
	}
	
	@Then("I enter correct OTP")
	public void i_enter_correct_OTP() throws Exception {

		//TODO
	}
	
}
